version: "3.9"
services:
  #Container do MySQL
  mysqlsrv:
    container_name: mysql_container
    image: mysql:5.7
    volumes:
      - /home/seu-perfil/docker/volumes/mysql:/var/lib/mysql-files
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank_account
    ports:
      - "3306:3306"

#docker run --name citi-mysql -e MYSQL_ROOT_PASSWORD=root -d mysql:tag